#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cantina.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_cantina")]
	public partial class cantinaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAluno(Aluno instance);
    partial void UpdateAluno(Aluno instance);
    partial void DeleteAluno(Aluno instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertContasReceber(ContasReceber instance);
    partial void UpdateContasReceber(ContasReceber instance);
    partial void DeleteContasReceber(ContasReceber instance);
    partial void InsertItensVenda(ItensVenda instance);
    partial void UpdateItensVenda(ItensVenda instance);
    partial void DeleteItensVenda(ItensVenda instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertStatusPagamento(StatusPagamento instance);
    partial void UpdateStatusPagamento(StatusPagamento instance);
    partial void DeleteStatusPagamento(StatusPagamento instance);
    partial void InsertVenda(Venda instance);
    partial void UpdateVenda(Venda instance);
    partial void DeleteVenda(Venda instance);
    #endregion
		
		public cantinaDataContext() : 
				base(global::cantina.DAL.Properties.Settings.Default.db_cantinaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public cantinaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cantinaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cantinaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cantinaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aluno> Aluno
		{
			get
			{
				return this.GetTable<Aluno>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<ContasReceber> ContasReceber
		{
			get
			{
				return this.GetTable<ContasReceber>();
			}
		}
		
		public System.Data.Linq.Table<ItensVenda> ItensVenda
		{
			get
			{
				return this.GetTable<ItensVenda>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produto
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<StatusPagamento> StatusPagamento
		{
			get
			{
				return this.GetTable<StatusPagamento>();
			}
		}
		
		public System.Data.Linq.Table<Venda> Venda
		{
			get
			{
				return this.GetTable<Venda>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_aluno")]
	public partial class Aluno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_aluno;
		
		private string _nome_aluno;
		
		private string _serie_aluno;
		
		private string _pai_aluno;
		
		private string _contato_pai;
		
		private EntitySet<Venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnSerieChanging(string value);
    partial void OnSerieChanged();
    partial void OnResponsavelChanging(string value);
    partial void OnResponsavelChanged();
    partial void OnContatoRespChanging(string value);
    partial void OnContatoRespChanged();
    #endregion
		
		public Aluno()
		{
			this._tb_venda = new EntitySet<Venda>(new Action<Venda>(this.attach_tb_venda), new Action<Venda>(this.detach_tb_venda));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_aluno", Storage="_id_aluno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._id_aluno;
			}
			set
			{
				if ((this._id_aluno != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._id_aluno = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_aluno", Storage="_nome_aluno", DbType="NVarChar(50)")]
		public string Nome
		{
			get
			{
				return this._nome_aluno;
			}
			set
			{
				if ((this._nome_aluno != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._nome_aluno = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serie_aluno", Storage="_serie_aluno", DbType="NVarChar(10)")]
		public string Serie
		{
			get
			{
				return this._serie_aluno;
			}
			set
			{
				if ((this._serie_aluno != value))
				{
					this.OnSerieChanging(value);
					this.SendPropertyChanging();
					this._serie_aluno = value;
					this.SendPropertyChanged("Serie");
					this.OnSerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="pai_aluno", Storage="_pai_aluno", DbType="NVarChar(50)")]
		public string Responsavel
		{
			get
			{
				return this._pai_aluno;
			}
			set
			{
				if ((this._pai_aluno != value))
				{
					this.OnResponsavelChanging(value);
					this.SendPropertyChanging();
					this._pai_aluno = value;
					this.SendPropertyChanged("Responsavel");
					this.OnResponsavelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="contato_pai", Storage="_contato_pai", DbType="NVarChar(50)")]
		public string ContatoResp
		{
			get
			{
				return this._contato_pai;
			}
			set
			{
				if ((this._contato_pai != value))
				{
					this.OnContatoRespChanging(value);
					this.SendPropertyChanging();
					this._contato_pai = value;
					this.SendPropertyChanged("ContatoResp");
					this.OnContatoRespChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Venda", Storage="_tb_venda", ThisKey="Codigo", OtherKey="CodigoAluno")]
		public EntitySet<Venda> Venda
		{
			get
			{
				return this._tb_venda;
			}
			set
			{
				this._tb_venda.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_tb_venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descricao;
		
		private EntitySet<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public Categoria()
		{
			this._Produto = new EntitySet<Produto>(new Action<Produto>(this.attach_Produto), new Action<Produto>(this.detach_Produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desc_categoria", Storage="_Descricao", DbType="NVarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Produto", Storage="_Produto", ThisKey="Codigo", OtherKey="CodigoCategoria")]
		public EntitySet<Produto> Produto
		{
			get
			{
				return this._Produto;
			}
			set
			{
				this._Produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produto(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Produto(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class ContasReceber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_conta;
		
		private System.Nullable<System.DateTime> _data_compra;
		
		private System.Nullable<System.DateTime> _data_vencimento;
		
		private System.Nullable<System.DateTime> _data_pagamento;
		
		private System.Nullable<int> _id_venda;
		
		private System.Nullable<int> _id_status;
		
		private EntityRef<StatusPagamento> _tb_status;
		
		private EntityRef<Venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoContaChanging(int value);
    partial void OnCodigoContaChanged();
    partial void OnDataCompraChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCompraChanged();
    partial void OnDataVencimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataVencimentoChanged();
    partial void OnDataPagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPagamentoChanged();
    partial void OnCodigoVendaChanging(System.Nullable<int> value);
    partial void OnCodigoVendaChanged();
    partial void OnCodigoStatusChanging(System.Nullable<int> value);
    partial void OnCodigoStatusChanged();
    #endregion
		
		public ContasReceber()
		{
			this._tb_status = default(EntityRef<StatusPagamento>);
			this._tb_venda = default(EntityRef<Venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_conta", Storage="_id_conta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoConta
		{
			get
			{
				return this._id_conta;
			}
			set
			{
				if ((this._id_conta != value))
				{
					this.OnCodigoContaChanging(value);
					this.SendPropertyChanging();
					this._id_conta = value;
					this.SendPropertyChanged("CodigoConta");
					this.OnCodigoContaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_compra", Storage="_data_compra", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCompra
		{
			get
			{
				return this._data_compra;
			}
			set
			{
				if ((this._data_compra != value))
				{
					this.OnDataCompraChanging(value);
					this.SendPropertyChanging();
					this._data_compra = value;
					this.SendPropertyChanged("DataCompra");
					this.OnDataCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_vencimento", Storage="_data_vencimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataVencimento
		{
			get
			{
				return this._data_vencimento;
			}
			set
			{
				if ((this._data_vencimento != value))
				{
					this.OnDataVencimentoChanging(value);
					this.SendPropertyChanging();
					this._data_vencimento = value;
					this.SendPropertyChanged("DataVencimento");
					this.OnDataVencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_pagamento", Storage="_data_pagamento", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataPagamento
		{
			get
			{
				return this._data_pagamento;
			}
			set
			{
				if ((this._data_pagamento != value))
				{
					this.OnDataPagamentoChanging(value);
					this.SendPropertyChanging();
					this._data_pagamento = value;
					this.SendPropertyChanged("DataPagamento");
					this.OnDataPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_id_venda", DbType="Int")]
		public System.Nullable<int> CodigoVenda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_id_status", DbType="Int")]
		public System.Nullable<int> CodigoStatus
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.OnCodigoStatusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("CodigoStatus");
					this.OnCodigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_tb_contas_receber", Storage="_tb_status", ThisKey="CodigoStatus", OtherKey="Codigo", IsForeignKey=true)]
		public StatusPagamento StatusPagamento
		{
			get
			{
				return this._tb_status.Entity;
			}
			set
			{
				StatusPagamento previousValue = this._tb_status.Entity;
				if (((previousValue != value) 
							|| (this._tb_status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_status.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._tb_status.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._id_status = value.Codigo;
					}
					else
					{
						this._id_status = default(Nullable<int>);
					}
					this.SendPropertyChanged("StatusPagamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_tb_contas_receber", Storage="_tb_venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				Venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._id_venda = value.CodigoVenda;
					}
					else
					{
						this._id_venda = default(Nullable<int>);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class ItensVenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _quantidade;
		
		private int _id_produto;
		
		private int _id_venda;
		
		private decimal _valor;
		
		private int _id_item;
		
		private EntityRef<Produto> _Produto;
		
		private EntityRef<Venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuantidadeChanging(int value);
    partial void OnQuantidadeChanged();
    partial void OnCodigoProdutoChanging(int value);
    partial void OnCodigoProdutoChanged();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnCodigoItemChanging(int value);
    partial void OnCodigoItemChanged();
    #endregion
		
		public ItensVenda()
		{
			this._Produto = default(EntityRef<Produto>);
			this._tb_venda = default(EntityRef<Venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="quantidade", Storage="_quantidade", DbType="Int NOT NULL")]
		public int Quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_id_produto", DbType="Int NOT NULL")]
		public int CodigoProduto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.OnCodigoProdutoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("CodigoProduto");
					this.OnCodigoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_id_venda", DbType="Int NOT NULL")]
		public int CodigoVenda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_item", Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoItem
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.OnCodigoItemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("CodigoItem");
					this.OnCodigoItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ItensVenda", Storage="_Produto", ThisKey="CodigoProduto", OtherKey="Codigo", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.ItensVenda.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.ItensVenda.Add(this);
						this._id_produto = value.Codigo;
					}
					else
					{
						this._id_produto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ItensVenda", Storage="_tb_venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				Venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.ItensVenda.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.ItensVenda.Add(this);
						this._id_venda = value.CodigoVenda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produtos")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descricao;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<int> _CodigoCategoria;
		
		private EntitySet<ItensVenda> _tb_itens_venda;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnCodigoCategoriaChanging(System.Nullable<int> value);
    partial void OnCodigoCategoriaChanged();
    #endregion
		
		public Produto()
		{
			this._tb_itens_venda = new EntitySet<ItensVenda>(new Action<ItensVenda>(this.attach_tb_itens_venda), new Action<ItensVenda>(this.detach_tb_itens_venda));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desc_produto", Storage="_Descricao", DbType="NVarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(25,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_CodigoCategoria", DbType="Int")]
		public System.Nullable<int> CodigoCategoria
		{
			get
			{
				return this._CodigoCategoria;
			}
			set
			{
				if ((this._CodigoCategoria != value))
				{
					this.OnCodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCategoria = value;
					this.SendPropertyChanged("CodigoCategoria");
					this.OnCodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ItensVenda", Storage="_tb_itens_venda", ThisKey="Codigo", OtherKey="CodigoProduto")]
		public EntitySet<ItensVenda> ItensVenda
		{
			get
			{
				return this._tb_itens_venda;
			}
			set
			{
				this._tb_itens_venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Produto", Storage="_Categoria", ThisKey="CodigoCategoria", OtherKey="Codigo", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Produto.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Produto.Add(this);
						this._CodigoCategoria = value.Codigo;
					}
					else
					{
						this._CodigoCategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itens_venda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_tb_itens_venda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status")]
	public partial class StatusPagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _status;
		
		private EntitySet<ContasReceber> _tb_contas_receber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public StatusPagamento()
		{
			this._tb_contas_receber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_tb_contas_receber), new Action<ContasReceber>(this.detach_tb_contas_receber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_tb_contas_receber", Storage="_tb_contas_receber", ThisKey="Codigo", OtherKey="CodigoStatus")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._tb_contas_receber;
			}
			set
			{
				this._tb_contas_receber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_receber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = this;
		}
		
		private void detach_tb_contas_receber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<decimal> _desconto;
		
		private System.Nullable<decimal> _valor_pago;
		
		private System.Nullable<int> _id_pessoa;
		
		private EntitySet<ContasReceber> _tb_contas_receber;
		
		private EntitySet<ItensVenda> _tb_itens_venda;
		
		private EntityRef<Aluno> _tb_aluno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnDescontoChanging(System.Nullable<decimal> value);
    partial void OnDescontoChanged();
    partial void OnValorPagoChanging(System.Nullable<decimal> value);
    partial void OnValorPagoChanged();
    partial void OnCodigoAlunoChanging(System.Nullable<int> value);
    partial void OnCodigoAlunoChanged();
    #endregion
		
		public Venda()
		{
			this._tb_contas_receber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_tb_contas_receber), new Action<ContasReceber>(this.detach_tb_contas_receber));
			this._tb_itens_venda = new EntitySet<ItensVenda>(new Action<ItensVenda>(this.attach_tb_itens_venda), new Action<ItensVenda>(this.detach_tb_itens_venda));
			this._tb_aluno = default(EntityRef<Aluno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoVenda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desconto", Storage="_desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OnDescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("Desconto");
					this.OnDescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor_pago", Storage="_valor_pago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ValorPago
		{
			get
			{
				return this._valor_pago;
			}
			set
			{
				if ((this._valor_pago != value))
				{
					this.OnValorPagoChanging(value);
					this.SendPropertyChanging();
					this._valor_pago = value;
					this.SendPropertyChanged("ValorPago");
					this.OnValorPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_id_pessoa", DbType="Int")]
		public System.Nullable<int> CodigoAluno
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					this.OnCodigoAlunoChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("CodigoAluno");
					this.OnCodigoAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_tb_contas_receber", Storage="_tb_contas_receber", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._tb_contas_receber;
			}
			set
			{
				this._tb_contas_receber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ItensVenda", Storage="_tb_itens_venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ItensVenda> ItensVenda
		{
			get
			{
				return this._tb_itens_venda;
			}
			set
			{
				this._tb_itens_venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Venda", Storage="_tb_aluno", ThisKey="CodigoAluno", OtherKey="Codigo", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._tb_aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._tb_aluno.Entity;
				if (((previousValue != value) 
							|| (this._tb_aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_aluno.Entity = null;
						previousValue.Venda.Remove(this);
					}
					this._tb_aluno.Entity = value;
					if ((value != null))
					{
						value.Venda.Add(this);
						this._id_pessoa = value.Codigo;
					}
					else
					{
						this._id_pessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_receber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_tb_contas_receber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
		
		private void attach_tb_itens_venda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_tb_itens_venda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
	}
}
#pragma warning restore 1591
